base:
    environment:
     - DC_NAME=dc1
     - COLLECT_METRICS=false
    dns: 
     - "127.0.0.1"
    privileged: true

hadoop:
    extends:
      file: base.yml
      service: base
    image: qnib/hadoop
    environment:
     - SUPERVISOR_SKIP_SRV=yarn,watchpsutil
    ports:
     - 8042
     - 8088
     - 50070

