consul:
    extends:
      file: base.yml
      service: base
    hostname: consul
    container_name: hadoop-consul
    image: qnib/consul
    environment:
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"

hadoop1:
    extends:
      file: base.yml
      service: hadoop
    hostname: hadoop1
    container_name: hadoop1
    environment:
     - HADOOP_HDFS_NAMENODE=true
     - HADOOP_YARN_RESOURCEMANAGER=true
    ports:
     - 8088:8088
    links:
     - consul:consul

hadoop2:
    extends:
      file: base.yml
      service: hadoop
    hostname: hadoop2
    container_name: hadoop2
    links:
     - consul:consul

hadoop3:
    extends:
      file: base.yml
      service: hadoop
    hostname: hadoop3
    container_name: hadoop3
    links:
     - consul:consul
